global:
  external_labels:
    monitor: 'kafka-monitor'

scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter:9308']
        labels:
          group: 'exporter'